Install pip packages as regular user
Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager.

diff --git a/xml/Dockerfile b/xml/Dockerfile
--- a/xml/Dockerfile
+++ b/xml/Dockerfile
@@ -33,16 +33,6 @@ RUN apk -U upgrade \
     && apk cache clean \
     && rm -rf /var/cache/apk/*
 
-RUN pip3 install --no-cache-dir --upgrade --break-system-packages \
-    gpxpy==1.6.2 \
-    tcx2gpx==0.1.5 \
-    yq==3.4.3 \
-    && msg="$(pip3 list --outdated | grep -i -e '^gpxpy ' -e '^tcx2gpx ' -e '^yq ' || true)" \
-    && if [ -n "${msg}" ]; then \
-       >&2 echo "ERROR: outdated: ${msg}" ; \
-       exit 1 ; \
-    fi
-
 RUN mkdir -p /opt/saxon
 
 COPY pom.xml mvnw run.sh /opt/saxon/
@@ -65,3 +55,13 @@ USER "${USER_NAME}"
 ENV HOME="${USER_HOME}"
 
 WORKDIR "${HOME}"
+
+RUN pip3 install --no-cache-dir --upgrade --break-system-packages \
+    gpxpy==1.6.2 \
+    tcx2gpx==0.1.5 \
+    yq==3.4.3 \
+    && msg="$(pip3 list --outdated | grep -i -e '^gpxpy ' -e '^tcx2gpx ' -e '^yq ' || true)" \
+    && if [ -n "${msg}" ]; then \
+       >&2 echo "ERROR: outdated: ${msg}" ; \
+       exit 1 ; \
+    fi
